version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # Porta padrão do RabbitMQ
      - "15672:15672" # Porta de gerenciamento do RabbitMQ

  ordersystem:
    build: .
    ports:
      - "8000:8000"  # REST API
      - "8080:8080"  # GraphQL API
      - "50051:50051"  # gRPC
    depends_on:
      - mysql
      - rabbitmq
    environment:
      DB_DRIVER: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: mysql
      DB_PORT: "3306"
      DB_NAME: orders
    command: >
      bash -c "
        echo 'Verificando diretórios e arquivos...';
        pwd && ls -la /app && ls -la /app/migrations;
        echo 'Aguardando MySQL...';
        sleep 10;
        echo 'Executando migrações...';
        migrate -path /app/migrations -database 'mysql://root:root@tcp(mysql:3306)/orders' up &&
        echo 'Iniciando aplicação...';
        ./ordersystem
      "

volumes:
  mysql_data:
